#!/usr/bin/env bash
# BlitzeCDN installer.
#
# Three jobs live here behind subcommands:
#
#   (no arguments)  build the virtualenv and install the pinned collections
#   standalone      provision this whole server as control plane and edge
#
# The no-argument form installs the current checkout for controller-only use.
set -Eeuo pipefail

readonly INSTALL_DIR=/opt/blitzecdn
readonly SERVICES=(
  blitzecdn-api.service
  blitzecdn-worker.service
)
readonly SYSTEMD_UNITS=(
  blitzecdn-api.service
  blitzecdn-worker.service
)
readonly CONFIG_DIR=/etc/blitzecdn
readonly CLI_WRAPPER=/usr/local/bin/blitzecdn
readonly SUDOERS_FILE=/etc/sudoers.d/blitzecdn-deploy
# Units and files a standalone install converges on this host through the edge
# roles. Each is BlitzeCDN-owned by construction (a BlitzeCDN-specific name or
# a BlitzeCDN marker line), so removing them never touches unrelated files.
readonly EDGE_MANAGED_UNITS=(
  blitzecdn-geoipupdate.service
  blitzecdn-geoipupdate.timer
)
readonly MANAGED_SITE_REGISTRY=/etc/nginx/blitzecdn-managed-sites
readonly EDGE_MANAGED_FILES=(
  "${MANAGED_SITE_REGISTRY}"
  /var/cache/nginx/blitzecdn
  /etc/systemd/resolved.conf.d/blitzecdn.conf
  /var/log/nginx/blitzecdn-access.log
  /etc/fail2ban/jail.d/blitzecdn-sshd.local
  /etc/ssh/sshd_config.d/50-blitzecdn.conf
  /etc/sysctl.d/60-blitzecdn.conf
  /etc/GeoIP.conf
)
readonly NGINX_MARKER='^# Managed by BlitzeCDN'
readonly USER_WRAPPER_MARKER='# Generated by the BlitzeCDN installer'

# Captured before dispatch strips the subcommand so destructive modes can
# re-exec a private copy after deleting the checkout that contained this file.
original_args=("$@")
# Removals that did not take, collected by remove_blitzecdn_artifacts and
# reported by require_clean_removal once the rest of the cleanup has run.
uninstall_failures=()
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

usage_root() {
  cat <<'EOF'
Usage: ./install.sh [SUBCOMMAND] [OPTIONS]

Install BlitzeCDN.

Subcommands:
  (none)      Build .venv and install the pinned Ansible collections
  standalone  Provision this server as an independent control plane and edge
  help        Show this message

Whole-host operations:
  --uninstall Remove every BlitzeCDN artifact and stop there
  --fresh     Uninstall, then reinstall like a brand-new server

Run './install.sh SUBCOMMAND --help' for the options of a subcommand.

Environment for the no-argument form:
  BLITZECDN_PYTHON     Python interpreter to build .venv with (default python3)
  BLITZECDN_DEV=1      Install -e '.[dev]' instead of a plain wheel
  BLITZECDN_WRAPPER_DIR
                       Where to put the `blitzecdn` command (default ~/.local/bin)
  BLITZECDN_USER_WRAPPER=0
                       Do not put `blitzecdn` on PATH; use .venv/bin/blitzecdn

The no-argument form installs a `blitzecdn` command that pins this checkout as
the project directory, so it can be run from any working directory.
EOF
}

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

# Fail with one or more stderr lines. The first argument is the exit status,
# because the CLI's documented codes matter here: 2 is invalid input and 1 is a
# host or environment that cannot be installed onto.
die() {
  local status=$1
  shift
  printf '%s\n' "$@" >&2
  exit "${status}"
}

# The uv release this installer pins, and the checksum of each build of it.
#
# Pinned rather than "latest", and verified against a hash that lives in this
# repository rather than one fetched beside the download. A checksum served
# from the same place as the artifact only proves the bytes arrived intact; it
# says nothing about whether the artifact is the one this release was tested
# against. Refresh both together with `just uv-pin VERSION`.
#
# One pin per release target. The Linux builds are what a server installs; the
# macOS builds exist because a controller-only checkout is a developer machine
# as often as a server, and a Linux binary unpacked onto a Mac fails with
# "cannot execute binary file" long after the checksum said the bytes were fine.
UV_VERSION="0.12.3"
# shellcheck disable=SC2034 # read by indirect expansion in ensure_uv
UV_SHA256_x86_64_unknown_linux_gnu="600cf9a742aca00d292673b16b5acffaa7b8c269a364ad0c2e79498dcb1fe101"
# shellcheck disable=SC2034 # read by indirect expansion in ensure_uv
UV_SHA256_aarch64_unknown_linux_gnu="bb66cb52e7b1823aed1183630d8d8e5c958840d584a4c55ec10a4cfc168dcca2"
# shellcheck disable=SC2034 # read by indirect expansion in ensure_uv
UV_SHA256_x86_64_apple_darwin="4c9f52262a14da336e4a42ed24992d12d0c956acde87619e4611d321dffa602b"
# shellcheck disable=SC2034 # read by indirect expansion in ensure_uv
UV_SHA256_aarch64_apple_darwin="546f7f8a6c70ff13a3a9d2bc958db3427298cebf3e0cb756f9177133b7068843"

# Print the SHA-256 of a file.
#
# `sha256sum` is coreutils and ships on every server this installs onto; macOS
# has `shasum` instead and only grows `sha256sum` if somebody installed GNU
# coreutils. Checking both means the verification below cannot be skipped for
# want of a tool name.
sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    die 1 "error: need sha256sum or shasum to verify the uv download"
  fi
}

# Print the path to a usable uv, downloading the pinned build if necessary.
#
# An operator's own uv is used when it is at least the pinned version: a server
# that already manages uv through its package manager should not grow a second
# copy. Anything older, or nothing at all, gets the pinned build unpacked into
# .state/bin — inside the installation rather than on the system, so uninstall
# removes it and no other software on the host is affected by our choice.
ensure_uv() {
  local existing
  if existing="$(command -v uv 2>/dev/null)" && [[ -x "${existing}" ]]; then
    local have
    have="$("${existing}" --version 2>/dev/null | awk '{print $2}')"
    if [[ -n "${have}" ]] &&
      [[ "$(printf '%s\n%s\n' "${UV_VERSION}" "${have}" | sort -V | head -1)" == "${UV_VERSION}" ]]; then
      printf '%s\n' "${existing}"
      return 0
    fi
  fi

  local vendored=".state/bin/uv"
  if [[ -x "${vendored}" ]] &&
    [[ "$("${vendored}" --version 2>/dev/null | awk '{print $2}')" == "${UV_VERSION}" ]]; then
    printf '%s\n' "${PWD}/${vendored}"
    return 0
  fi

  # Both halves of the target triple are detected. Deriving only the
  # architecture and assuming Linux is what put a Linux binary on a Mac.
  local system machine platform architecture target pin expected
  system="$(uname -s)"
  machine="$(uname -m)"
  case "${system}" in
    Linux) platform="unknown-linux-gnu" ;;
    Darwin) platform="apple-darwin" ;;
    *)
      die 1 "error: no pinned uv build for ${system}; install uv ${UV_VERSION} or newer and rerun"
      ;;
  esac
  case "${machine}" in
    x86_64 | amd64) architecture="x86_64" ;;
    aarch64 | arm64) architecture="aarch64" ;;
    *)
      die 1 "error: no pinned uv build for ${machine}; install uv ${UV_VERSION} or newer and rerun"
      ;;
  esac
  target="${architecture}-${platform}"
  pin="UV_SHA256_${target//-/_}"
  expected="${!pin-}"
  [[ -n "${expected}" ]] ||
    die 1 "error: no pinned checksum for ${target}; install uv ${UV_VERSION} or newer and rerun"

  command -v curl >/dev/null 2>&1 ||
    die 1 "error: curl is required to download uv; install it and rerun"

  local archive
  archive="$(mktemp)"
  # shellcheck disable=SC2064 # expand the path now, while it is still in scope
  trap "rm -f -- '${archive}'" RETURN

  # stderr, not stdout: this function returns the uv path on stdout, and a
  # progress line there ends up substituted into the caller's variable.
  echo "Downloading uv ${UV_VERSION} (${target})..." >&2
  # --retry covers the 5xx and connection resets the release CDN serves now and
  # then; without it a single bad second fails a whole provisioning run. The
  # checksum below is what makes a retried download safe to trust.
  curl -fsSL --proto '=https' --tlsv1.2 \
    --retry 3 --retry-connrefused --retry-all-errors --retry-delay 2 \
    -o "${archive}" \
    "https://github.com/astral-sh/uv/releases/download/${UV_VERSION}/uv-${target}.tar.gz" ||
    die 1 "error: could not download uv ${UV_VERSION}"

  local actual
  actual="$(sha256_of "${archive}")"
  [[ "${actual}" == "${expected}" ]] ||
    die 1 \
      "error: the uv download does not match its pinned checksum" \
      "       expected ${expected}" \
      "       received ${actual}" \
      "       Refusing to run it. Retry, and if it persists, do not proceed."

  mkdir -p .state/bin
  tar -xzf "${archive}" -C .state/bin --strip-components=1 \
    "uv-${target}/uv" ||
    die 1 "error: could not unpack uv ${UV_VERSION}"
  chmod 0755 "${vendored}"
  printf '%s\n' "${PWD}/${vendored}"
}

# Guard a privileged subcommand. Every caller reports the same thing, so the
# EUID test exists once — the test harness neutralises this single line to
# exercise the destructive paths as an unprivileged user.
require_root() {
  [[ ${EUID} -eq 0 ]] || die 1 "error: run this ${1:-installer} with sudo"
}

# Assert that the option in $1 was given the value in $2. Callers pass their
# remaining arguments, so the option names itself in the message.
require_value() {
  [[ $# -ge 2 ]] || die 2 "error: $1 needs a value"
}

# Reject an unrecognised option and show the subcommand's own help, so the
# reader sees the options that do exist rather than the top-level summary.
reject_unknown_option() {
  local option=$1 usage=$2
  echo "error: unknown option: ${option}" >&2
  "${usage}" >&2
  exit 2
}

# Re-exec this script from a private copy in /tmp, once.
#
# The two removal paths delete the directory this file lives in. A shell reads
# its script lazily, so it would otherwise continue from a path that no longer
# exists. The guard variable is passed
# by name and re-exported, so the copy knows not to copy itself again; that
# second pass is also where the copy arranges to delete itself on exit.
reexec_from_private_copy() {
  local guard=$1 label=$2
  if [[ ${!guard:-0} == 1 ]]; then
    # Deferred expansion: $0 is the copy, and functions do not change it.
    trap 'rm -f -- "$0"' EXIT
    return 0
  fi
  local copy
  copy=$(mktemp "/tmp/blitzecdn-${label}.XXXXXX")
  install -m 0700 -- "$0" "${copy}"
  exec env "${guard}=1" "${copy}" "${original_args[@]}"
}

# Git against the installation checkout. `safe.directory` is needed because the
# working tree belongs to blitzecdn while `--fresh` runs as root.
repo_git() {
  git -c safe.directory="${INSTALL_DIR}" -C "${INSTALL_DIR}" "$@"
}

# `--fresh` fetches code from origin and then runs it as root, so it accepts
# only the upstream repository rather than trusting an arbitrary remote.
require_upstream_origin() {
  local remote_url
  remote_url=$(repo_git remote get-url origin) ||
    die 1 "error: ${INSTALL_DIR} has no origin remote"
  case "${remote_url}" in
    https://github.com/misaf/blitze-cdn-cp|https://github.com/misaf/blitze-cdn-cp.git|\
    git@github.com:misaf/blitze-cdn-cp.git) ;;
    *) die 1 "error: refusing unexpected origin URL: ${remote_url}" ;;
  esac
  printf '%s\n' "${remote_url}"
}

# Run the CLI as the service account. Used by the installer before the wrapper
# at ${CLI_WRAPPER} necessarily exists, and independent of it afterwards.
run_blitzecdn() {
  runuser -u blitzecdn -- env \
    PATH="${INSTALL_DIR}/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
    BLITZE_PROJECT_DIR="${INSTALL_DIR}" \
    BLITZE_ALLOW_EMPTY_SITES="${BLITZE_ALLOW_EMPTY_SITES:-false}" \
    "${INSTALL_DIR}/.venv/bin/blitzecdn" "$@"
}

# Converge this host through the control-plane role.
#
# Ansible owns the Linux state here exactly as it owns an edge's: accounts,
# ownership, sudo, the loopback SSH trust, the CLI wrapper, the environment
# file, and the systemd units. The installer's remaining job is to make this
# call possible — packages, virtualenv, collections — and then to hand over.
converge_control_plane() {
  local ansible_tmp
  ansible_tmp=$(mktemp -d)
  # Ansible's temporary files must not land in .state. This play runs as root
  # and gives .state to the service account, and a root-owned leftover there
  # would break the next command run as that account.
  ANSIBLE_CONFIG=ansible/ansible.cfg ANSIBLE_LOCAL_TEMP="${ansible_tmp}" \
    "${INSTALL_DIR}/.venv/bin/ansible-playbook" \
    ansible/playbooks/control-plane.yml "$@"
  rm -rf -- "${ansible_tmp}"
}

# Put `blitzecdn` on the invoking user's PATH, pinned to this checkout.
#
# The CLI takes its project directory from BLITZE_PROJECT_DIR and otherwise
# falls back to the working directory, so `.venv/bin/blitzecdn` is only correct
# when it runs from the checkout. Pinning that directory is the whole point of
# the wrapper — without it, running from anywhere would silently read and write
# state next to wherever the operator happened to be standing.
#
#   BLITZECDN_USER_WRAPPER=0  skip it (the server installs use this)
#   BLITZECDN_WRAPPER_DIR     write it somewhere other than ~/.local/bin
install_user_wrapper() {
  [[ "${BLITZECDN_USER_WRAPPER:-1}" != 0 ]] || return 0

  local wrapper_dir="${BLITZECDN_WRAPPER_DIR:-${HOME:-}/.local/bin}"
  if [[ -z ${BLITZECDN_WRAPPER_DIR:-} && -z ${HOME:-} ]]; then
    echo "warning: HOME is unset; skipping the ${script_dir}/.venv/bin/blitzecdn shortcut" >&2
    return 0
  fi
  local wrapper="${wrapper_dir}/blitzecdn"

  # Never overwrite a command this installer did not write. A hand-rolled
  # wrapper or an unrelated program of the same name stays as it is.
  if [[ -e ${wrapper} ]] &&
    ! grep -Fq -- "${USER_WRAPPER_MARKER}" "${wrapper}" 2>/dev/null; then
    echo "warning: ${wrapper} exists and was not written by this installer; leaving it" >&2
    echo "         run this checkout with ${script_dir}/.venv/bin/blitzecdn" >&2
    return 0
  fi

  mkdir -p -- "${wrapper_dir}"
  # printf %q rather than bash 4.4 ${var@Q}: the no-argument install is the form
  # contributors run, and macOS still ships bash 3.2.
  local quoted_dir wrapper_tmp
  quoted_dir=$(printf '%q' "${script_dir}")
  wrapper_tmp=$(mktemp)
  cat > "${wrapper_tmp}" <<EOF
#!/usr/bin/env bash
${USER_WRAPPER_MARKER}. Do not edit: re-running install.sh in the checkout
# below rewrites this file, and installing from a second checkout repoints it.
set -euo pipefail
exec env BLITZE_PROJECT_DIR=${quoted_dir} ${quoted_dir}/.venv/bin/blitzecdn "\$@"
EOF
  install -m 0755 "${wrapper_tmp}" "${wrapper}"
  rm -f -- "${wrapper_tmp}"

  case ":${PATH}:" in
    *":${wrapper_dir}:"*)
      echo "Installed ${wrapper}; run 'blitzecdn' from any directory."
      ;;
    *)
      # Name the file the invoking shell actually reads. zsh — the default on
      # macOS since Catalina — never sources ~/.profile, so the generic advice
      # leaves the operator with a command that is still not found.
      local login_rc=.profile
      [[ ${SHELL##*/} == zsh ]] && login_rc=.zprofile
      echo "Installed ${wrapper}, which is not on your PATH yet. Add it with:"
      echo "  echo 'export PATH=\"${wrapper_dir}:\${PATH}\"' >> \"\${HOME}\"/${login_rc}"
      ;;
  esac
}

# ---------------------------------------------------------------------------
# (no arguments) — virtualenv and collections
# ---------------------------------------------------------------------------

# shellcheck disable=SC2120 # taking no arguments is this form's contract
cmd_install() {
  [[ $# -eq 0 ]] || {
    echo "error: the default install takes no arguments: $*" >&2
    usage_root >&2
    exit 2
  }

  cd -- "${script_dir}"

  local python_command="${BLITZECDN_PYTHON:-python3}"
  command -v "${python_command}" >/dev/null 2>&1 ||
    die 1 "error: ${python_command} was not found; install Python 3.12 or newer"

  "${python_command}" -c '
import sys
if sys.version_info[:2] < (3, 12):
    raise SystemExit("error: BlitzeCDN requires Python 3.12 or newer")
'

  local uv
  uv="$(ensure_uv)"

  if [[ -e .venv && ! -x .venv/bin/python ]]; then
    local invalid_venv
    invalid_venv=".venv.invalid.$(date -u +%Y%m%dT%H%M%SZ)"
    echo "warning: .venv is incomplete; preserving it as ${invalid_venv}" >&2
    mv -- .venv "${invalid_venv}"
  fi

  # `uv sync` builds exactly the environment uv.lock describes, which is what
  # makes two servers installed a month apart identical. It also *removes*
  # anything else in .venv, so every runtime requirement has to be a real
  # dependency in pyproject.toml — ansible-core included.
  #
  # --frozen refuses to re-resolve: a lockfile that does not match pyproject
  # fails the install rather than quietly installing something nobody tested.
  #
  # BLITZECDN_DEV=1 adds the test and lint tooling and makes src/ edits take
  # effect without reinstalling. Without it the venv holds what a server wants
  # and nothing else.
  local -a sync_flags=(--frozen --python "${python_command}")
  if [[ "${BLITZECDN_DEV:-0}" == "1" ]]; then
    "${uv}" sync "${sync_flags[@]}"
  else
    "${uv}" sync "${sync_flags[@]}" --no-dev --no-editable
  fi

  [[ -x .venv/bin/python && -x .venv/bin/blitzecdn ]] ||
    die 1 "error: uv created an incomplete .venv; rerun with --fresh"

  # Collections go inside the repository rather than ~/.ansible/collections:
  # ansible/ansible.cfg looks here first, tests/test_contract.py reads whatever
  # lands here, and a lab machine can hold several checkouts without them
  # fighting over one global collection path.
  local collections_path=.state/collections

  # ansible/ansible.cfg already resolves collections_path to that directory
  # (relative entries there resolve against the config file, not the caller's
  # working directory). Exporting it keeps ansible-galaxy from warning that it is
  # installing somewhere Ansible will not look, which is not true at deploy time.
  export ANSIBLE_CONFIG=ansible/ansible.cfg

  # Only third-party dependencies now: the BlitzeCDN roles live in
  # ansible/roles/ and ship with this checkout, so there is nothing to pin, to
  # build, or to keep in step with the desired-state contract.
  .venv/bin/ansible-galaxy collection install \
    -r ansible/requirements.yml -p "${collections_path}"

  .venv/bin/blitzecdn setup

  echo
  echo "Installation complete. Run commands with .venv/bin/blitzecdn"
  install_user_wrapper
}

# ---------------------------------------------------------------------------
# standalone — provision this server
# ---------------------------------------------------------------------------

usage_standalone() {
  cat <<'EOF'
Usage: sudo ./install.sh standalone --admin-cidr CIDR --email ADDRESS [OPTIONS]

Install one independent BlitzeCDN control plane and edge on this server.

Required:
  --admin-cidr CIDR  Network allowed to administer SSH, for example 203.0.113.8/32
  --email ADDRESS    Default ACME account email

Options:
  --deploy            Run the initial edge deployment (default: prepare only)
  --allow-empty-sites Permit --deploy to remove every previously managed site
  --public-address ADDRESS
                      Public edge IP or hostname; repeat when needed (NAT safe)
  -h, --help         Show this help

The checkout must be /opt/blitzecdn because the hardened systemd units use that
path. Re-running the installer preserves the API key, inventory, and state.
EOF
}

cmd_standalone() {
  local admin_cidr='' acme_email='' run_deploy=0 allow_empty_sites=0
  local public_addresses=()

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --admin-cidr)
        require_value "$@"
        admin_cidr=$2
        shift 2
        ;;
      --email)
        require_value "$@"
        acme_email=$2
        shift 2
        ;;
      --deploy)
        run_deploy=1
        shift
        ;;
      --allow-empty-sites)
        allow_empty_sites=1
        shift
        ;;
      --public-address)
        require_value "$@"
        public_addresses+=("$2")
        shift 2
        ;;
      -h|--help)
        usage_standalone
        exit 0
        ;;
      *) reject_unknown_option "$1" usage_standalone ;;
    esac
  done

  require_root
  [[ -n ${admin_cidr} ]] || die 2 "error: --admin-cidr is required"
  [[ -n ${acme_email} ]] || die 2 "error: --email is required"

  [[ ${script_dir} == "${INSTALL_DIR}" ]] ||
    die 1 "error: clone or copy this release to ${INSTALL_DIR}, then run the installer there"
  cd -- "${script_dir}"

  # Everything up to `converge_control_plane` is bootstrap: the least this host
  # needs before Ansible can run on it. The operating-system check, the rest of
  # the packages, the accounts, the SSH trust, the units and the environment
  # file all belong to the role, which converges them the same way the edge
  # roles converge an edge.
  # python3 is the interpreter uv builds the virtualenv around — uv creates the
  # environment itself, so python3-venv is no longer needed. curl fetches the
  # pinned uv build when the host has no uv of its own; ca-certificates is what
  # makes that fetch verifiable at all, and a minimal image can lack it. git is
  # here because ansible/requirements.yml fetches the edge collection from a Git
  # ref, and that happens in the default install form below — before the role runs.
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y ca-certificates curl git python3

  # Validated as soon as there is an interpreter to validate with, and before
  # the host is converged: a typo then costs a package install rather than a
  # provisioned server that has to be corrected afterwards. A minimal image may
  # genuinely have no python3 until the line above installs it.
  python3 - "${admin_cidr}" "${acme_email}" <<'PY'
import ipaddress
import sys

try:
    ipaddress.ip_network(sys.argv[1], strict=False)
except ValueError as error:
    raise SystemExit(f"error: invalid --admin-cidr: {error}") from error
email = sys.argv[2]
if email.count("@") != 1 or any(char.isspace() for char in email):
    raise SystemExit("error: --email must be a valid email address")
PY


  # The virtualenv is built as root because the service account does not exist
  # yet; the role hands the whole tree over immediately afterwards. The per-user
  # wrapper belongs to a developer checkout, and this host gets the root-owned
  # command from the role instead.
  export BLITZECDN_USER_WRAPPER=0
  # shellcheck disable=SC2119 # the default form deliberately takes no arguments
  cmd_install

  converge_control_plane \
    --extra-vars "blitzecdn_controlplane_acme_email=${acme_email}"

  # Registering the edge and deploying are control-plane decisions, so they stay
  # with the CLI that records them.
  if ! run_blitzecdn edge list --json \
    | grep -Eq '"name"[[:space:]]*:[[:space:]]*"edge-local"'; then
    local edge_add_args=(
      edge add edge-local
      --host localhost --user deploy --ssh-source "${admin_cidr}"
    )
    local public_address
    for public_address in "${public_addresses[@]}"; do
      edge_add_args+=(--public-address "${public_address}")
    done
    run_blitzecdn "${edge_add_args[@]}"
  elif [[ ${#public_addresses[@]} -gt 0 ]]; then
    local edge_update_args=(edge update edge-local)
    local public_address
    for public_address in "${public_addresses[@]}"; do
      edge_update_args+=(--public-address "${public_address}")
    done
    run_blitzecdn "${edge_update_args[@]}"
  fi

  if [[ ${run_deploy} -eq 1 ]]; then
    if [[ -s ${MANAGED_SITE_REGISTRY} ]] && [[ $(run_blitzecdn site list) == "[]" ]] \
      && [[ ${allow_empty_sites} -ne 1 ]]; then
      die 1 "error: this edge has managed sites but desired state is empty" \
        "Recreate the desired sites first, or rerun with --deploy --allow-empty-sites to remove them."
    fi
    if [[ ${allow_empty_sites} -eq 1 ]]; then
      BLITZE_ALLOW_EMPTY_SITES=true run_blitzecdn deploy --yes
    else
      run_blitzecdn deploy --yes
    fi
  else
    echo "Initial deployment skipped (safe default). Run: blitzecdn deploy"
  fi

  echo
  echo "Standalone BlitzeCDN installation complete."
  echo "API credentials live in ${CONFIG_DIR}/blitzecdn.env; read it with sudo."
  echo "Connect from your workstation with your existing operator account and key:"
  echo "  ssh -L 8000:127.0.0.1:8000 OPERATOR@THIS_SERVER"
  echo "API:     http://127.0.0.1:8000"
  echo "Status:  systemctl status blitzecdn-api.service"
}

# ---------------------------------------------------------------------------
# uninstall / fresh — remove every artifact, or wipe and rebuild clean
# ---------------------------------------------------------------------------

usage_uninstall() {
  cat <<'EOF'
Usage: sudo ./install.sh --uninstall [OPTIONS]

Remove every BlitzeCDN artifact from this host and stop there, leaving the
system packages it had and nothing BlitzeCDN wrote.

Options:
  --yes        Do not ask for confirmation
  -h, --help   Show this help

Removed:
  - the installation directory /opt/blitzecdn and everything in it: source,
    .venv, .env, and .state (database, certificates, collections, locks, logs)
  - the services, timers, and systemd unit files
  - /etc/blitzecdn and the API credentials it holds
  - the /usr/local/bin/blitzecdn command
  - the sudo rule /etc/sudoers.d/blitzecdn-deploy
  - the blitzecdn and deploy accounts and their homes
  - the edge-managed nginx sites, certificates, cache, and drop-ins this host
    converged as an edge

Nothing outside those paths is changed and no packages are removed. The
uninstaller first copies itself outside the installation directory, so it keeps
working even when that directory is deleted, and it is safe to run twice.
EOF
}

usage_fresh() {
  cat <<'EOF'
Usage: sudo ./install.sh --fresh [OPTIONS] [STANDALONE OPTIONS]

Uninstall BlitzeCDN completely, then install it again exactly as a brand-new
server is installed: clone the running release from origin and run the
standalone installer. The standalone options pass through unchanged:

  --admin-cidr CIDR  Network allowed to administer SSH
  --email ADDRESS    Default ACME account email
  --public-address ADDRESS
                     Public edge IP or hostname; repeat when needed
  --deploy           Run the initial edge deployment (default: prepare only)
  --allow-empty-sites
                     Permit --deploy to remove every previously managed site

Options:
  --yes        Do not ask for confirmation before uninstalling
  -h, --help   Show this help

The current checkout must be a Git clone whose origin is the upstream
repository, so the rebuild reinstalls the exact release that is running. Run
EOF
}

confirm_destructive() {
  local assume_yes="$1" mode="$2"
  [[ ${assume_yes} == 1 ]] && return 0
  cat >&2 <<'EOF'
This removes every BlitzeCDN artifact on this host and cannot be undone:

  - /opt/blitzecdn and all state in it (database, certificates, collections)
  - the BlitzeCDN services and systemd unit files
  - /etc/blitzecdn and the API credentials it holds
  - the /usr/local/bin/blitzecdn command
  - the sudo rule /etc/sudoers.d/blitzecdn-deploy
  - the blitzecdn and deploy accounts and their homes
  - the edge-managed nginx sites and certificates on this host
EOF
  if [[ ${mode} == fresh ]]; then
    echo >&2 "Afterwards it re-clones the current release and reinstalls it."
  fi
  local answer
  read -r -p "Continue? [y/N]: " answer
  [[ ${answer} =~ ^[Yy]$ ]] || { echo "Cancelled."; exit 0; }
}

remove_service_account() {
  local account="$1" expected_home="$2"
  local passwd_entry home
  if passwd_entry=$(getent passwd "${account}"); then
    home=$(printf '%s\n' "${passwd_entry}" | cut -d: -f6)
    if [[ ${home} != "${expected_home}" ]]; then
      echo "warning: leaving ${account} alone (its home is ${home}, not ${expected_home})" >&2
      return 0
    fi
    # The installer's own loopback SSH check logs the deployment account in.
    # Ask logind to close its sessions first, then explicitly stop anything it
    # does not track (notably Ansible's persistent SSH control processes).
    # Restrict both signals to the account already verified above: uninstalling
    # must not leave one of its processes behind and then pretend userdel worked.
    if command -v loginctl >/dev/null 2>&1; then
      loginctl terminate-user "${account}" >/dev/null 2>&1 || true
    fi
    if command -v pgrep >/dev/null 2>&1 &&
      command -v pkill >/dev/null 2>&1 &&
      pgrep -u "${account}" >/dev/null 2>&1; then
      pkill -TERM -u "${account}" >/dev/null 2>&1 || true
      local waited=0
      while [[ ${waited} -lt 10 ]] && pgrep -u "${account}" >/dev/null 2>&1; do
        sleep 1
        waited=$((waited + 1))
      done
      if pgrep -u "${account}" >/dev/null 2>&1; then
        pkill -KILL -u "${account}" >/dev/null 2>&1 || true
      fi
    fi

    if command -v userdel >/dev/null 2>&1; then
      # `-r` also removes the home and mail spool, and exits non-zero when it
      # cannot even though the account itself is gone. Retry without it, then
      # judge by whether the account still resolves rather than by either exit
      # status — that is the only question that matters here.
      userdel -r "${account}" >/dev/null 2>&1 ||
        userdel "${account}" >/dev/null 2>&1 || true
    fi
    if getent passwd "${account}" >/dev/null; then
      # Almost always a process still running as the account: userdel refuses
      # while one exists, and the loopback SSH check a standalone installation
      # runs can leave a session behind. Name the holders — without them the
      # operator has no way to tell what to stop.
      local holders=''
      if command -v pgrep >/dev/null 2>&1; then
        holders=$(pgrep -u "${account}" -l 2>/dev/null | tr '\n' ',' | sed 's/,$//') || true
      fi
      uninstall_failures+=(
        "${account}: the account still exists${holders:+ (still running: ${holders})}"
      )
    fi
  fi
  rm -rf -- "${expected_home}"
}

# Fail after the cleanup rather than in the middle of it. Everything removable
# is removed first, so a retry has less to do and the operator sees one accurate
# list instead of whichever failure happened to come first. Reporting success
# with an account still on the host is the outcome this exists to prevent.
require_clean_removal() {
  [[ ${#uninstall_failures[@]} -eq 0 ]] || die 1 \
    "error: BlitzeCDN was not fully removed:" \
    "${uninstall_failures[@]/#/  - }" \
    "Stop whatever still uses the account — 'loginctl terminate-user ACCOUNT'," \
    "or kill the processes listed — then run the uninstaller again."
}

remove_blitzecdn_artifacts() {
  local unit conf link removed_nginx=0

  systemctl stop "${SERVICES[@]}" "${EDGE_MANAGED_UNITS[@]}" 2>/dev/null || true
  systemctl disable "${SERVICES[@]}" "${EDGE_MANAGED_UNITS[@]}" 2>/dev/null || true
  for unit in "${SYSTEMD_UNITS[@]}" "${EDGE_MANAGED_UNITS[@]}"; do
    rm -f -- "/etc/systemd/system/${unit}"
  done
  systemctl daemon-reload 2>/dev/null || true

  rm -rf -- "${CONFIG_DIR}" "${CLI_WRAPPER}" "${SUDOERS_FILE}"
  rm -rf -- "${INSTALL_DIR}"

  remove_service_account blitzecdn /var/lib/blitzecdn
  remove_service_account deploy /home/deploy

  # Nginx configurations carry the BlitzeCDN marker as their first line, so a
  # content match finds every site this host converged — including ones the
  # managed-site registry never learned about — and no configuration an
  # operator wrote themselves.
  for conf in /etc/nginx/conf.d/*.conf /etc/nginx/sites-available/*.conf; do
    [[ -f ${conf} ]] || continue
    if grep -q "${NGINX_MARKER}" "${conf}"; then
      link="/etc/nginx/sites-enabled/$(basename -- "${conf}")"
      rm -f -- "${link}"
      rm -f -- "${conf}"
      removed_nginx=1
    fi
  done
  rm -rf -- "${EDGE_MANAGED_FILES[@]}"
  if [[ ${removed_nginx} -eq 1 ]] && command -v nginx >/dev/null 2>&1; then
    nginx -t >/dev/null 2>&1 && systemctl reload nginx 2>/dev/null || true
  fi
}

cmd_uninstall() {
  local assume_yes=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --yes)
        assume_yes=1
        shift
        ;;
      -h|--help)
        usage_uninstall
        exit 0
        ;;
      *) reject_unknown_option "$1" usage_uninstall ;;
    esac
  done

  require_root uninstaller

  # The cleanup deletes the directory this file lives in.
  reexec_from_private_copy BLITZECDN_UNINSTALL_REEXEC uninstall

  confirm_destructive "${assume_yes}" uninstall
  remove_blitzecdn_artifacts
  require_clean_removal

  echo
  echo "BlitzeCDN has been removed. No packages were removed and nothing outside"
  echo "the paths listed in the confirmation was changed."
}

cmd_fresh() {
  local assume_yes=0
  local fresh_args=()
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --yes)
        assume_yes=1
        shift
        ;;
      -h|--help)
        usage_fresh
        exit 0
        ;;
      *)
        fresh_args=("$@")
        break
        ;;
    esac
  done

  require_root

  # Same reason as --uninstall, and it shares the guard: --fresh runs that
  # cleanup before it re-clones.
  reexec_from_private_copy BLITZECDN_UNINSTALL_REEXEC fresh

  # The re-clone needs the origin and the running release, so read them from
  # the checkout before the cleanup removes it.
  [[ -d ${INSTALL_DIR}/.git ]] || die 1 \
    "error: ${INSTALL_DIR} is not a Git checkout; nothing to reinstall from" \
    "Run --uninstall instead, or clone the release to ${INSTALL_DIR} first."

  local remote_url
  remote_url=$(require_upstream_origin)

  # Preserve the source identity of the running checkout. An exact release tag
  # stays on that release, the supported 2.x line stays attached to that branch,
  # and any other development checkout is pinned to its exact commit. All of
  # this is read before the cleanup, because the cleanup deletes the checkout.
  local revision
  revision=$(repo_git describe --tags --exact-match HEAD 2>/dev/null || true)
  local named_revision=1
  if [[ -z ${revision} ]]; then
    revision=$(repo_git symbolic-ref --quiet --short HEAD 2>/dev/null || true)
    if [[ ${revision} != "2.x" ]]; then
      revision=$(repo_git rev-parse HEAD)
      named_revision=0
    fi
  fi

  confirm_destructive "${assume_yes}" fresh
  remove_blitzecdn_artifacts
  # Rebuilding on top of a half-removed host is how a "fresh" install inherits
  # the state it was meant to discard.
  require_clean_removal

  if [[ ${named_revision} -eq 1 ]]; then
    git clone --branch "${revision}" "${remote_url}" "${INSTALL_DIR}"
  else
    git clone "${remote_url}" "${INSTALL_DIR}"
    git -C "${INSTALL_DIR}" checkout --detach "${revision}"
  fi

  echo
  echo "Reinstalling the running release from a clean state..."
  # `${fresh_args[@]+...}` keeps this legal on bash 3.2 (macOS), where an empty
  # array expands to an unbound-variable error under `set -u`.
  "${INSTALL_DIR}/install.sh" standalone ${fresh_args[@]+"${fresh_args[@]}"}
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

subcommand=install
if [[ $# -gt 0 ]]; then
  case "$1" in
    standalone)
      subcommand=$1
      shift
      ;;
    install)
      subcommand=install
      shift
      ;;
    --uninstall)
      subcommand=uninstall
      shift
      ;;
    --fresh)
      subcommand=fresh
      shift
      ;;
    help|-h|--help)
      usage_root
      exit 0
      ;;
  esac
fi

"cmd_${subcommand}" "$@"
