"""Post-bootstrap work invoked by ``install.sh`` through the installed runtime."""

from __future__ import annotations

import argparse
import shlex
import sys
from collections.abc import Sequence
from pathlib import Path

from blitzecdn.bootstrap import ControlPlane, build_control_plane
from blitzecdn.capabilities.deployments.domain import DeploymentStatus
from blitzecdn.capabilities.edges.domain import Edge, EdgePatch
from blitzecdn.core.config import Settings

_WRAPPER_MARKER = "# Generated by the BlitzeCDN installer"


def install_wrapper(project_dir: Path, wrapper_dir: Path) -> tuple[str, bool]:
    """Install or repoint the per-user command without replacing foreign files."""
    wrapper = wrapper_dir / "blitzecdn"
    if wrapper.exists() and _WRAPPER_MARKER not in wrapper.read_text(
        encoding="utf-8", errors="ignore"
    ):
        return (
            f"warning: {wrapper} exists and was not written by this installer; "
            "leaving it",
            False,
        )
    wrapper_dir.mkdir(parents=True, exist_ok=True)
    quoted = shlex.quote(str(project_dir))
    wrapper.write_text(
        "#!/usr/bin/env bash\n"
        f"{_WRAPPER_MARKER}. Do not edit: re-running install.sh in the checkout\n"
        "# below rewrites this file, and installing from a second checkout "
        "repoints it.\n"
        "set -euo pipefail\n"
        f'exec env BLITZE_PROJECT_DIR={quoted} {quoted}/.venv/bin/blitzecdn "$@"\n',
        encoding="utf-8",
    )
    wrapper.chmod(0o755)
    return f"Installed {wrapper}", True


def finalize_standalone(
    control: ControlPlane,
    *,
    admin_cidr: str,
    public_addresses: Sequence[str],
    deploy: bool,
) -> DeploymentStatus | None:
    """Record the local edge and optionally perform the first deployment."""
    known = {edge.name for edge in control.edges.list_edges()}
    addresses = tuple(public_addresses)
    if "edge-local" not in known:
        control.edges.add_edge(
            Edge(
                name="edge-local",
                host="localhost",
                user="deploy",
                public_addresses=addresses,
                ssh_sources=(admin_cidr,),
            ),
            "installer",
        )
    elif public_addresses:
        control.edges.update_edge(
            "edge-local", EdgePatch(public_addresses=addresses), "installer"
        )
    if not deploy:
        return None
    return control.deployments.deploy("installer").status


def main(arguments: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="blitzecdn-install-handoff")
    commands = parser.add_subparsers(dest="command", required=True)
    wrapper = commands.add_parser("wrapper")
    wrapper.add_argument("--project-dir", type=Path, required=True)
    wrapper.add_argument("--wrapper-dir", type=Path, required=True)
    standalone = commands.add_parser("standalone")
    standalone.add_argument("--admin-cidr", required=True)
    standalone.add_argument("--public-address", action="append", default=[])
    standalone.add_argument("--deploy", action="store_true")
    options = parser.parse_args(arguments)

    if options.command == "wrapper":
        message, installed = install_wrapper(options.project_dir, options.wrapper_dir)
        print(message, file=sys.stdout if installed else sys.stderr)
        if not installed:
            print(
                f"run this checkout with {options.project_dir}/.venv/bin/blitzecdn",
                file=sys.stderr,
            )
        return 0

    control = build_control_plane(Settings.from_environment())
    try:
        result = finalize_standalone(
            control,
            admin_cidr=options.admin_cidr,
            public_addresses=options.public_address,
            deploy=options.deploy,
        )
    finally:
        control.close()
    if result is None:
        print("Initial deployment skipped (safe default). Run: blitzecdn deploy")
        return 0
    return 0 if result is DeploymentStatus.SUCCEEDED else 5


if __name__ == "__main__":
    raise SystemExit(main())
