"""Which operations each delivery surface carries, declared rather than inferred.

`test_frozen` holds the CLI and the HTTP API to their golden files
independently, which catches a surface that *changed* but says nothing about
the two agreeing. A route added without its command, or a command without its
route, is invisible there: both goldens are regenerated by the same
`just refreeze` and both diffs look intentional.

They are not meant to agree everywhere. `blitzecdn config set` edits a `.env`
on the control-plane host and `GET /metrics` answers a Prometheus scrape;
neither has any business having a counterpart. What was missing is the
*record* of which asymmetries are deliberate — without it, the certificate
upload and request endpoints sat without commands for as long as they existed,
because nothing ever asked.

So the map below is the record, and it is exhaustive by construction: a new
command or a new route that nobody classified fails the two tests underneath,
with the entry it needs. Adding a row is cheap. Being made to add one is the
whole point, because the row is where an author has to say out loud whether the
other surface should have grown too.

The pairing is by *operation*, not by shape. Fifteen `domain` commands map to
one `PATCH /v1/domains/{domain}`: the CLI names the intent an operator has and
the API takes the patch a client already computed, and that difference is
deliberate — see the module docstring of `blitzecdn.capabilities.dns.cli`.
"""

from __future__ import annotations

import frozen_surfaces as surfaces
from frozen_surfaces import installed

#: One row per operation: the distribution that owns it, the command, the
#: route, and — for a row that names only one of the two — why the other
#: surface does not carry it. A row with both needs no note; the pairing is
#: the statement.
#:
#: `None` on the CLI side is not automatically a gap to close. It is a claim
#: that the operation is not one an operator types, and the note has to make
#: that case.
_DELIVERY: tuple[tuple[str, str | None, str | None, str], ...] = (
    # -- Zones: policy edits, all landing on the one patch route -----------
    ("blitzecdn", "domain add", "POST /v1/domains", ""),
    ("blitzecdn", "domain list", "GET /v1/domains", ""),
    ("blitzecdn", "domain show", "GET /v1/domains/{domain}", ""),
    ("blitzecdn", "domain remove", "DELETE /v1/domains/{domain}", ""),
    ("blitzecdn", "domain enable", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain origin", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain ssl", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain ssl-automatic", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain minimum-tls", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain always-use-https", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain http3", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain max-upload-size", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain cache", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain cache-query-string", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain compression", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain firewall", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain under-attack", "PATCH /v1/domains/{domain}", ""),
    ("blitzecdn", "domain visitor-headers", "PATCH /v1/domains/{domain}", ""),
    # -- Derived hosts: read-only on both sides ----------------------------
    ("blitzecdn", "domain hosts", "GET /v1/hosts", ""),
    (
        "blitzecdn",
        None,
        "GET /v1/hosts/{name}",
        "one derived host by name. `domain hosts` prints the whole set and an "
        "operator greps it; a client fetching one host by name would rather "
        "not receive the fleet.",
    ),
    (
        "blitzecdn",
        None,
        "GET /v1/domains/{domain}/resolve",
        "what a hostname resolves to once the rules are applied — a preview a "
        "UI shows beside the rule being edited. The CLI's answer to the same "
        "question is `rule show` plus `domain hosts`.",
    ),
    # -- Records -----------------------------------------------------------
    ("blitzecdn", "record add", "POST /v1/domains/{domain}/records", ""),
    ("blitzecdn", "record list", "GET /v1/domains/{domain}/records", ""),
    ("blitzecdn", "record proxy", "PATCH /v1/domains/{domain}/records/{name}", ""),
    ("blitzecdn", "record unproxy", "PATCH /v1/domains/{domain}/records/{name}", ""),
    ("blitzecdn", "record remove", "DELETE /v1/domains/{domain}/records/{name}", ""),
    ("blitzecdn", "dns export", "GET /v1/dns/export", ""),
    # -- Rules -------------------------------------------------------------
    ("blitzecdn", "rule add", "POST /v1/domains/{domain}/rules", ""),
    ("blitzecdn", "rule list", "GET /v1/domains/{domain}/rules", ""),
    ("blitzecdn", "rule show", "GET /v1/domains/{domain}/rules/{name}", ""),
    ("blitzecdn", "rule set", "PATCH /v1/domains/{domain}/rules/{name}", ""),
    ("blitzecdn", "rule remove", "DELETE /v1/domains/{domain}/rules/{name}", ""),
    # -- Edges -------------------------------------------------------------
    ("blitzecdn", "edge add", "POST /v1/edges", ""),
    ("blitzecdn", "edge list", "GET /v1/edges", ""),
    ("blitzecdn", "edge update", "PATCH /v1/edges/{name}", ""),
    ("blitzecdn", "edge remove", "DELETE /v1/edges/{name}", ""),
    (
        "blitzecdn",
        None,
        "GET /v1/edges/{name}",
        "one edge by name; see GET /v1/hosts/{name}.",
    ),
    (
        "blitzecdn",
        "edge image spec",
        None,
        "the pinned edge image and its digest, read out of this checkout's own "
        "version pins. It describes the installed control plane rather than "
        "any state it holds, which is the same reason `plugins` is here.",
    ),
    # -- Durable work ------------------------------------------------------
    (
        "blitzecdn",
        "job list",
        None,
        "what background work is queued, running or failed. Deliberately not a "
        "route: a job is control-plane machinery rather than a resource a "
        "client manages, and the two things a client actually wants — did my "
        "deployment run, did my certificate renew — are already answered by "
        "`GET /v1/deployments/{deployment_id}` and `GET /v1/workflows`. "
        "Publishing the queue would be publishing an implementation.",
    ),
    ("blitzecdn", "job show", None, "one job, and the error that ended it; see above."),
    (
        "blitzecdn",
        "job schedules",
        None,
        "when each recurring job is next due. Same reasoning: the schedule is "
        "how the control plane paces itself, not a resource, and a client that "
        "wants a certificate renewed now asks for that rather than waiting on "
        "a timer.",
    ),
    # -- Releases ----------------------------------------------------------
    ("blitzecdn", "release list", "GET /v1/releases", ""),
    ("blitzecdn", "release show", "GET /v1/releases/{release_id}", ""),
    ("blitzecdn", "release show", "GET /v1/releases/current", ""),
    (
        "blitzecdn",
        "release artifact",
        "GET /v1/releases/{release_id}/artifacts/{name}",
        "",
    ),
    (
        "blitzecdn",
        "release explain",
        None,
        "where each effective setting came from. The route answers it too — an "
        "explanation is part of every release document — so a client asking "
        "`GET /v1/releases/{release_id}` already has it and needs no endpoint "
        "of its own. The command exists because a terminal wants one host's "
        "settings rather than the fleet's.",
    ),
    # -- Deployments -------------------------------------------------------
    ("blitzecdn", "deploy", "POST /v1/deployments", ""),
    ("blitzecdn", "status", "GET /v1/deployments", ""),
    ("blitzecdn", "status", "GET /v1/deployments/{deployment_id}", ""),
    (
        "blitzecdn",
        "status",
        "GET /v1/deployments/{deployment_id}/targets",
        "how far each edge got. `blitzecdn status <id>` prints it beneath the "
        "deployment, because an operator asking about a run wants the per-edge "
        "answer in the same breath; a client polling a rollout wants to fetch "
        "just the progress without re-reading the deployment each time.",
    ),
    ("blitzecdn", "rollback", "POST /v1/rollbacks", ""),
    ("blitzecdn", "drift", "POST /v1/drift", ""),
    (
        "blitzecdn",
        None,
        "GET /v1/deployments/{deployment_id}/drift",
        "the drift a past deployment recorded. `blitzecdn drift` measures it "
        "now, which is the question at a terminal; reading an old deployment's "
        "answer is the question a dashboard asks.",
    ),
    ("blitzecdn", "audit", "GET /v1/audit-events", ""),
    (
        "blitzecdn",
        None,
        "GET /v1/workflows",
        "progress of an operation still running. A command *is* the operation "
        "and prints as it goes, so it has nothing to poll; an HTTP client that "
        "started one has only this.",
    ),
    ("blitzecdn", None, "GET /v1/workflows/{workflow_id}", "see GET /v1/workflows."),
    (
        "blitzecdn",
        "plan",
        None,
        "what a deploy would do, without doing it. Reads the same state "
        "`deploy` would and writes nothing, so an HTTP caller can have the "
        "answer by not calling POST /v1/deployments.",
    ),
    # -- Diagnostics: about this install, not about the fleet --------------
    (
        "blitzecdn",
        None,
        "GET /health",
        "a readiness probe, for whatever restarts this process. Nobody types "
        "it; `doctor` is the question an operator asks.",
    ),
    ("blitzecdn", None, "GET /metrics", "a Prometheus scrape target."),
    (
        "blitzecdn",
        "doctor",
        None,
        "checks the host this runs on — the database, the Ansible tree, the "
        "SSH keys, the resolver. Every answer is about the machine the command "
        "is typed on, and served over HTTP it would describe a machine the "
        "caller is not on.",
    ),
    (
        "blitzecdn",
        "validate",
        None,
        "refuses a deploy that would render a broken vhost. Reachable over "
        "HTTP only as the deploy it precedes, which runs it.",
    ),
    (
        "blitzecdn",
        "plugins",
        None,
        "which capability wheels this install has. Describes the control plane "
        "itself; see `edge image spec`.",
    ),
    (
        "blitzecdn",
        "ansible roles-path",
        None,
        "the resolved role search path on this host.",
    ),
    ("blitzecdn", "ansible slots", None, "see `ansible roles-path`."),
    # -- The install itself ------------------------------------------------
    (
        "blitzecdn",
        "init",
        None,
        "writes the `.env` this control plane reads. It runs before there is a "
        "control plane to serve anything, which is what keeps all four of "
        "these off the API.",
    ),
    ("blitzecdn", "setup", None, "creates the schema; see `init`."),
    ("blitzecdn", "serve", None, "starts the API. It cannot be one of its own routes."),
    (
        "blitzecdn",
        "config list",
        None,
        "reads and writes the `.env`; see `init`. Exposing it would also let "
        "an API caller change the credentials the API authenticates with.",
    ),
    ("blitzecdn", "config set", None, "see `config list`."),
    ("blitzecdn", "config unset", None, "see `config list`."),
    # -- Optional wheels ---------------------------------------------------
    ("blitzecdn_cache", "cache purge", "POST /v1/cache/purge", ""),
    ("blitzecdn_cache", "stats", "POST /v1/cache/stats", ""),
    ("blitzecdn_origins", "origin check", "POST /v1/origins/check", ""),
    ("blitzecdn_certificates", "cert list", "GET /v1/certificates", ""),
    (
        "blitzecdn_certificates",
        "cert preflight",
        "GET /v1/hosts/{name}/certificate/preflight",
        "",
    ),
    ("blitzecdn_certificates", "cert renew", "POST /v1/certificates/renew", ""),
    ("blitzecdn_certificates", "cert reconcile", "POST /v1/certificates/reconcile", ""),
    (
        "blitzecdn_certificates",
        "cert upload",
        "POST /v1/hosts/{name}/certificate/upload",
        "",
    ),
    (
        "blitzecdn_certificates",
        "cert request",
        "POST /v1/hosts/{name}/certificate/request",
        "",
    ),
    ("blitzecdn_certificates", "ssl reconcile", "POST /v1/ssl/automatic/reconcile", ""),
    (
        "blitzecdn_certificates",
        None,
        "GET /v1/hosts/{name}/certificate",
        "one host's certificate. `cert list` prints the fleet's, sorted by "
        "expiry, which is the form a human wants; see GET /v1/hosts/{name}.",
    ),
    (
        "blitzecdn_backup",
        "backup create",
        None,
        "reads and writes archives on the control-plane host, including the "
        "ACME account key. Over HTTP it would be an endpoint that hands the "
        "caller every private key the control plane holds.",
    ),
    ("blitzecdn_backup", "backup inspect", None, "see `backup create`."),
    ("blitzecdn_backup", "backup restore", None, "see `backup create`."),
)


def _declared(index: int) -> set[str]:
    """One side of the map, for the distributions this environment has.

    Filtered by `installed` for the same reason `test_frozen` filters its
    goldens: `just test-core-only` runs with no optional wheel, and a row
    naming one of their commands is correct there and simply absent.
    """
    return {
        row[index] for row in _DELIVERY if row[index] is not None and installed(row[0])
    }


def _live_commands() -> set[str]:
    return {
        line.split("\t")[2].split("\t")[0].removeprefix("blitzecdn ")
        for line in surfaces.cli_surface().splitlines()
    }


def _live_routes(settings) -> set[str]:
    return {
        line.split("\t")[2]
        for line in surfaces.http_surface(settings).splitlines()
        if line.split("\t")[1] == "route"
    }


def _report(kind: str, unclassified: set[str], stale: set[str]) -> str:
    problems = []
    if unclassified:
        problems.append(
            f"{kind} present in this tree but not in _DELIVERY: "
            + ", ".join(sorted(unclassified))
            + ". Add a row saying whether the other surface should carry this "
            "operation too — and if it should not, why."
        )
    if stale:
        problems.append(
            f"_DELIVERY names {kind} that no longer exist: "
            + ", ".join(sorted(stale))
            + ". Remove the rows, or the map is describing a surface this tree "
            "does not have."
        )
    return "\n\n".join(problems)


def test_every_command_is_classified():
    """No command without a row, and no row without a command."""
    live = _live_commands()
    declared = _declared(1)
    report = _report("commands", live - declared, declared - live)
    assert not report, report


def test_every_route_is_classified(settings):
    """No route without a row, and no row without a route."""
    live = _live_routes(settings)
    declared = _declared(2)
    report = _report("routes", live - declared, declared - live)
    assert not report, report


def test_a_one_sided_operation_says_why():
    """A row naming one surface has to make the case; a paired row need not.

    The note is the whole value of a one-sided row. Without it the map records
    that an asymmetry exists, which anyone could see by diffing the two golden
    files, rather than that somebody decided it.
    """
    silent = sorted(
        row[1] or row[2] or "?"
        for row in _DELIVERY
        if (row[1] is None) != (row[2] is None) and not row[3].strip()
    )
    assert not silent, (
        "these operations are on one surface only and say nothing about why: "
        + ", ".join(silent)
    )


def test_every_failure_kind_reaches_both_surfaces():
    """Neither delivery layer may leave a `FailureKind` unanswered.

    The two projections are the same decision made twice — what a failure is,
    stated as a number a caller can branch on — and they drifted precisely
    because nothing held them together. Both classified exceptions themselves,
    from their own ordered list, and an unmapped `BlitzeError` came out as exit
    2 (`INVALID_INPUT`, "you typed it wrong") on the command line and 503 ("the
    service is down, retry") over HTTP. Both cannot be true of one error.

    Core now owns the taxonomy and each layer owns only its projection, so the
    drift this test forbids is narrower than it was: not two lists of exception
    types disagreeing, but one of the two tables failing to cover a kind. Both
    are subscripted rather than `.get()`, so an uncovered kind is a `KeyError`
    at the moment a failure is being reported — the worst time to discover it.
    """
    from blitzecdn.api.app import _HTTP_STATUS
    from blitzecdn.cli.main import _EXIT_CODES
    from blitzecdn.core.exceptions import FailureKind

    missing = {
        "exit codes (blitzecdn.cli.main._EXIT_CODES)": set(FailureKind)
        - set(_EXIT_CODES),
        "HTTP statuses (blitzecdn.api.app._HTTP_STATUS)": set(FailureKind)
        - set(_HTTP_STATUS),
    }
    report = "; ".join(
        f"{table} does not answer {sorted(k.value for k in kinds)}"
        for table, kinds in missing.items()
        if kinds
    )
    assert not report, report


def test_every_error_class_is_classified():
    """Every `BlitzeError` subclass names a kind deliberately.

    `classify` falls back to INTERNAL so that an unclassified error is at worst
    honest rather than a lie about the operator's input. That fallback is a
    safety net, not the place to leave a class: INTERNAL tells a caller "this
    installation is broken", which is wrong for an error that is actually a
    conflict or a missing thing. So the net is checked here rather than relied
    on, and a new subclass has to say which kind it is.
    """
    from blitzecdn.core import exceptions
    from blitzecdn.core.exceptions import BlitzeError, PluginError

    classification = exceptions._CLASSIFICATION
    classified = {kind for kind, _ in classification}
    subclasses = {
        value
        for value in vars(exceptions).values()
        if isinstance(value, type)
        and issubclass(value, BlitzeError)
        and value is not BlitzeError
    }
    unclassified = sorted(cls.__name__ for cls in subclasses - classified)
    assert not unclassified, (
        "these BlitzeError subclasses fall through to the INTERNAL default: "
        + ", ".join(unclassified)
        + ". Add each to _CLASSIFICATION with the kind it actually is."
    )
    # The ordering the walk depends on: a subclass listed below its base can
    # never be reached, and `DeploymentBusyError` under `ConflictError` is
    # exactly that mistake waiting to be made again.
    for position, (kind, _) in enumerate(classification):
        for later, _ in classification[position + 1 :]:
            assert not issubclass(later, kind) or later is kind, (
                f"{kind.__name__} is a base of {later.__name__} but is listed "
                "before it, so the subclass can never match"
            )
    assert exceptions.classify(PluginError("x")) is exceptions.FailureKind.INTERNAL
