"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# Autogenerated columns render custom types by their full path, so the module
# that defines them has to be importable here. Without this line every
# migration touching a timestamp column fails on a NameError at upgrade time —
# on a server, mid-install.
import blitzecdn.core.database_models  # noqa: F401
${imports if imports else ""}

revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
