"""The control-plane schema.

Revision ID: 0001
Revises:
Create Date: 2026-08-12

The whole schema in one revision, because there is no installation older than
it. A new database is created directly from the models and stamped here; this
exists so that a *future* schema change has a base to migrate from, and so the
shape on disk is reviewable as code rather than only as model definitions.

Generated with `just db-revision`, which diffs
:mod:`blitzecdn.core.persistence.tables` against the database.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# Autogenerated columns render custom types by their full path, so the module
# that defines them has to be importable here. Without this line every
# migration touching a timestamp column fails on a NameError at upgrade time —
# on a server, mid-install.
import blitzecdn.core.persistence.tables

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ansible_settings",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sqlite.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.Column("operator", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("details", sqlite.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("payload", sqlite.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("dedupe_key", sa.String(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.Column(
            "leased_until",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=True,
        ),
        sa.Column("leased_by", sa.String(), nullable=True),
        sa.Column("fence", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.Column(
            "finished_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=True,
        ),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')",
            name="jobs_status_check",
        ),
        sa.CheckConstraint("attempts >= 0", name="jobs_attempts_check"),
        sa.CheckConstraint("max_attempts >= 1", name="jobs_max_attempts_check"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_jobs_created_at"), ["created_at"], unique=False
        )
        # Partial, so the single-flight guarantee binds only while a job is
        # unfinished: a scheduled job that ran an hour ago must not keep the
        # next firing out of the queue.
        batch_op.create_index(
            "ix_jobs_dedupe_key_unfinished",
            ["dedupe_key"],
            unique=True,
            sqlite_where=sa.text("status IN ('pending', 'running')"),
        )
        batch_op.create_index("ix_jobs_leased_until", ["leased_until"], unique=False)
        batch_op.create_index(
            "ix_jobs_status_available_at", ["status", "available_at"], unique=False
        )

    op.create_table(
        "job_schedules",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("jitter_seconds", sa.Integer(), nullable=False),
        sa.Column("lease_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "next_run_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.Column(
            "last_run_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=True,
        ),
        sa.CheckConstraint(
            "interval_seconds >= 1", name="job_schedules_interval_check"
        ),
        sa.CheckConstraint("lease_seconds >= 1", name="job_schedules_lease_check"),
        sa.PrimaryKeyConstraint("name"),
    )
    with op.batch_alter_table("job_schedules", schema=None) as batch_op:
        batch_op.create_index(
            "ix_job_schedules_next_run_at", ["next_run_at"], unique=False
        )

    op.create_table(
        "release_inputs",
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("document", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_table(
        "releases",
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("compiler_version", sa.Integer(), nullable=False),
        sa.Column("inputs_digest", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.Column("document", sqlite.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inputs_digest"],
            ["release_inputs.digest"],
        ),
        sa.PrimaryKeyConstraint("digest"),
    )
    with op.batch_alter_table("releases", schema=None) as batch_op:
        batch_op.create_index("ix_releases_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_releases_id", ["id"], unique=True)

    op.create_table(
        "deployments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("operator", sa.String(), nullable=False),
        sa.Column("check_mode", sa.Boolean(), nullable=False),
        sa.Column("rollback_of", sa.String(), nullable=True),
        sa.Column("host_limit", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.Column(
            "started_at", blitzecdn.core.persistence.tables.UtcDateTime(), nullable=True
        ),
        sa.Column(
            "finished_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=True,
        ),
        sa.Column("result", sqlite.JSON(), nullable=True),
        sa.Column("release_id", sa.String(), nullable=False),
        sa.Column("canonical_digest", sa.String(), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rollback_of"],
            ["deployments.id"],
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', "
            "'timed_out', 'abandoned')",
            name="deployments_status_check",
        ),
        sa.CheckConstraint(
            "rollback_of IS NULL OR rollback_of != id",
            name="deployments_no_self_rollback_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deployments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deployments_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deployments_rollback_of"), ["rollback_of"], unique=False
        )
        batch_op.create_index("ix_deployments_release_id", ["release_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_deployments_status_created_at"),
            ["status", "created_at"],
            unique=False,
        )

    op.create_table(
        "deployment_targets",
        sa.Column("deployment_id", sa.String(), nullable=False),
        sa.Column("edge", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("phase", sa.String(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("fence", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=True,
        ),
        sa.Column(
            "finished_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=True,
        ),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], ondelete="CASCADE"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'skipped')",
            name="deployment_targets_status_check",
        ),
        sa.CheckConstraint(
            "phase IS NULL OR phase IN "
            "('prepare', 'validate', 'stage', 'activate', 'verify')",
            name="deployment_targets_phase_check",
        ),
        sa.PrimaryKeyConstraint("deployment_id", "edge"),
    )
    with op.batch_alter_table("deployment_targets", schema=None) as batch_op:
        batch_op.create_index(
            "ix_deployment_targets_deployment_id", ["deployment_id"], unique=False
        )

    op.create_table(
        "domains",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("policy", sqlite.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.CheckConstraint("length(name) > 0", name="domains_name_nonempty_check"),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "zone_rules",
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("match", sa.String(), nullable=False),
        sa.Column("overrides", sqlite.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["domain"], ["domains.name"], ondelete="CASCADE"),
        sa.CheckConstraint("length(name) > 0", name="zone_rules_name_nonempty_check"),
        sa.CheckConstraint("length(match) > 0", name="zone_rules_match_nonempty_check"),
        sa.CheckConstraint(
            "priority BETWEEN 1 AND 1000", name="zone_rules_priority_check"
        ),
        sa.PrimaryKeyConstraint("domain", "name"),
    )
    op.create_table(
        "deployment_requirements",
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column(
            "requested_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("kind"),
    )
    op.create_table(
        "edges",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("user", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("private_key_file", sa.String(), nullable=True),
        sa.Column("public_addresses", sqlite.JSON(), nullable=False),
        sa.Column("ssh_sources", sqlite.JSON(), nullable=False),
        sa.Column("capabilities", sqlite.JSON(), nullable=True),
        sa.Column(
            "updated_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.CheckConstraint("length(name) > 0", name="edges_name_nonempty_check"),
        sa.CheckConstraint("port BETWEEN 1 AND 65535", name="edges_port_check"),
        sa.CheckConstraint("length(host) > 0", name="edges_host_nonempty_check"),
        sa.CheckConstraint("length(user) > 0", name="edges_user_nonempty_check"),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "workflows",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("operator", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.Column("steps", sqlite.JSON(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.CheckConstraint(
            "kind <> '' AND length(kind) <= 64 AND kind = lower(kind)",
            name="workflows_kind_check",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'needs_review')",
            name="workflows_status_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflows_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "workflows_status_idx", ["status", "created_at"], unique=False
        )

    op.create_table(
        "dns_records",
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("ttl", sa.Integer(), nullable=False),
        sa.Column("proxied", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["domain"], ["domains.name"], ondelete="CASCADE"),
        sa.CheckConstraint("ttl BETWEEN 1 AND 604800", name="dns_records_ttl_check"),
        sa.CheckConstraint("type IN ('A', 'AAAA')", name="dns_records_type_check"),
        sa.CheckConstraint("length(name) > 0", name="dns_records_name_nonempty_check"),
        sa.CheckConstraint(
            "value IS NOT NULL AND length(value) > 0",
            name="dns_records_value_check",
        ),
        sa.PrimaryKeyConstraint("domain", "name", "type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dns_records")
    op.drop_table("deployment_requirements")
    with op.batch_alter_table("deployment_targets", schema=None) as batch_op:
        batch_op.drop_index("ix_deployment_targets_deployment_id")

    op.drop_table("deployment_targets")
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.drop_index("workflows_status_idx")

    op.drop_table("workflows")
    op.drop_table("edges")
    op.drop_table("zone_rules")
    op.drop_table("domains")
    with op.batch_alter_table("deployments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deployments_status"))
        batch_op.drop_index(batch_op.f("ix_deployments_created_at"))

    op.drop_table("deployments")
    with op.batch_alter_table("releases", schema=None) as batch_op:
        batch_op.drop_index("ix_releases_id")
        batch_op.drop_index("ix_releases_created_at")

    op.drop_table("releases")
    op.drop_table("release_inputs")
    with op.batch_alter_table("job_schedules", schema=None) as batch_op:
        batch_op.drop_index("ix_job_schedules_next_run_at")

    op.drop_table("job_schedules")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_status_available_at")
        batch_op.drop_index("ix_jobs_leased_until")
        batch_op.drop_index("ix_jobs_dedupe_key_unfinished")
        batch_op.drop_index(batch_op.f("ix_jobs_created_at"))

    op.drop_table("jobs")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_created_at"))

    op.drop_table("audit_events")
    op.drop_table("ansible_settings")
    # ### end Alembic commands ###
