"""The control-plane schema.

Revision ID: 0001
Revises:
Create Date: 2026-08-12

The whole schema in one revision, because there is no installation older than
it. A new database is created directly from the models and stamped here; this
exists so that a *future* schema change has a base to migrate from, and so the
shape on disk is reviewable as code rather than only as model definitions.

Generated with `just db-revision`, which diffs
:mod:`blitzecdn.core.persistence.tables` against the database.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# Autogenerated columns render custom types by their full path, so the module
# that defines them has to be importable here. Without this line every
# migration touching a timestamp column fails on a NameError at upgrade time —
# on a server, mid-install.
import blitzecdn.core.persistence.tables

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ansible_settings",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sqlite.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.Column("operator", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("details", sqlite.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_events_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "deployments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("operator", sa.String(), nullable=False),
        sa.Column("check_mode", sa.Boolean(), nullable=False),
        sa.Column("rollback_of", sa.String(), nullable=True),
        sa.Column("host_limit", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.Column(
            "started_at", blitzecdn.core.persistence.tables.UtcDateTime(), nullable=True
        ),
        sa.Column(
            "finished_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=True,
        ),
        sa.Column("result", sqlite.JSON(), nullable=True),
        sa.Column("snapshot", sa.String(), nullable=False),
        sa.Column("canonical_digest", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rollback_of"],
            ["deployments.id"],
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', "
            "'timed_out', 'abandoned')",
            name="deployments_status_check",
        ),
        sa.CheckConstraint(
            "rollback_of IS NULL OR rollback_of != id",
            name="deployments_no_self_rollback_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deployments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deployments_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deployments_status"), ["status"], unique=False
        )

    op.create_table(
        "domains",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "updated_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.CheckConstraint("length(name) > 0", name="domains_name_nonempty_check"),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "deployment_requirements",
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column(
            "requested_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("kind"),
    )
    op.create_table(
        "edges",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("user", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("private_key_file", sa.String(), nullable=True),
        sa.Column("public_addresses", sqlite.JSON(), nullable=False),
        sa.Column("ssh_sources", sqlite.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.CheckConstraint("port BETWEEN 1 AND 65535", name="edges_port_check"),
        sa.CheckConstraint("length(host) > 0", name="edges_host_nonempty_check"),
        sa.CheckConstraint("length(user) > 0", name="edges_user_nonempty_check"),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "projection_state",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source_revision", sa.String(), nullable=False),
        sa.Column(
            "projected_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "sites",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("server_names", sqlite.JSON(), nullable=False),
        sa.Column("origin_host", sa.String(), nullable=False),
        sa.Column("policy", sqlite.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "workflows",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("operator", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.Column("steps", sqlite.JSON(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('deployment', 'rollback', 'certificate')",
            name="workflows_kind_check",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'needs_review')",
            name="workflows_status_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.create_index(
            "workflows_status_idx", ["status", "updated_at"], unique=False
        )

    op.create_table(
        "dns_records",
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("ttl", sa.Integer(), nullable=False),
        sa.Column("site", sa.String(), nullable=True),
        sa.Column(
            "updated_at",
            blitzecdn.core.persistence.tables.UtcDateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["domain"], ["domains.name"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["site"],
            ["sites.name"],
            name="dns_records_site_fkey",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint("ttl BETWEEN 1 AND 604800", name="dns_records_ttl_check"),
        sa.CheckConstraint("type IN ('A', 'AAAA')", name="dns_records_type_check"),
        sa.CheckConstraint("length(name) > 0", name="dns_records_name_nonempty_check"),
        sa.CheckConstraint(
            "(value IS NULL) <> (site IS NULL)", name="dns_records_target_check"
        ),
        sa.CheckConstraint(
            "value IS NULL OR length(value) > 0",
            name="dns_records_value_nonempty_check",
        ),
        sa.PrimaryKeyConstraint("domain", "name", "type"),
    )
    with op.batch_alter_table("dns_records", schema=None) as batch_op:
        batch_op.create_index("ix_dns_records_site", ["site"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dns_records", schema=None) as batch_op:
        batch_op.drop_index("ix_dns_records_site")

    op.drop_table("dns_records")
    op.drop_table("deployment_requirements")
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.drop_index("workflows_status_idx")

    op.drop_table("workflows")
    op.drop_table("sites")
    op.drop_table("projection_state")
    op.drop_table("edges")
    op.drop_table("domains")
    with op.batch_alter_table("deployments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deployments_status"))
        batch_op.drop_index(batch_op.f("ix_deployments_created_at"))

    op.drop_table("deployments")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_created_at"))

    op.drop_table("audit_events")
    op.drop_table("ansible_settings")
    # ### end Alembic commands ###
